### ISSUE TITLE
ACT Error When Loading

### ISSUE THREAD

**Issue by ghost** [Elysia-ff/FFXIV_RotationHelper#12]
Hello,

The following error happens when loading a URL: 

```
System.ArgumentException - An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at FFXIV_RotationHelper.DB.<LoadDB>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_RotationHelper.DB.<LoadAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_RotationHelper.FFXIV_RotationHelper.<GetRotationAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFXIV_RotationHelper.FFXIV_RotationHelper.<LoadBtn_Click>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

System.ThrowHelper, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
```

Character is found successfully, and plugin description under "Plugin Listing" shows "Plugin started".
Started happening a day or so ago, was working since EW launch previously.
Tried using old OverlayPlugin / FFXIV_ACT_Plugin, but no dice.

**Comment by SecondReality** [comment]
I wonder if this was related to changes of ffxivrotations.com - skills have been updated there.

**Comment by SecondReality** [comment]
@majuula I reverted a file on ffxivrotations.com that the rotation helper might have been using (I'm not sure exactly).
Could you try it again and see if it works now?

**Comment by ghost** [comment]
@SecondReality That fixed it, works fine for me now, thanks :).
Though, new skills don't show up atm, assuming since it was reverted.

**Comment by Elysia-ff** [comment]
@majuula  I'm working on update for EW release now. I'll let you know when I'm done :)

**Comment by Elysia-ff** [comment]
@majuula A new update has been released.
All the new skills including reaper's and sage's should work now.
